Repository codeit-sprint-fullstack/4-sprint-mission-fe, pull requests merged in 2024-11, with the labels that each got.

#18 [조형민] sprint1,2
  README.md
  css/reset.css
  css/style.css
  img/eye.png
  img/eye_disable.png
  img/google.png
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/img_home_01.png
  img/img_home_02.png
  img/img_home_03.png
  img/img_home_bottom.png
  img/img_home_top.png
  img/kakao.png
  img/logo.png
  index.html
  login/index.html
  signup/index.html
Labels: 매운맛🔥, 최종 제출

#17 [구은모] sprint1,2
  faq.html
  img/Component 2.png
  img/Component 2@2x.png
  img/Component 2@3x.png
  img/Component 3.png
  img/Component 3@2x.png
  img/Component 3@3x.png
  img/Group 33682.png
  img/Group.png
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_bottom.png
  img/Img_home_bottom@2x.png
  img/Img_home_bottom@3x.png
  img/Img_home_top.png
  img/Img_home_top@2x.png
  img/Img_home_top@3x.png
  img/Property 1=lg.png
  img/Property 1=lg@2x.png
  img/Property 1=lg@3x.png
  img/Vector.png
  img/btn_visibility_off_24px.png
  img/btn_visibility_off_24px.png:Zone.Identifier
  img/ic_facebook.png
  img/ic_twitter.png
  img/state=active.png
  img/state=active.png:Zone.Identifier
  img/type=solid, status=default.png
  img/type=solid, status=default.png:Zone.Identifier
  index.html
  items.html
  login.html
  privacy.html
  reset.css
  signup.html
  style.css
Labels: 매운맛🔥, 최종 제출

#4 Basic 이현서 sprint1
  Frame 2609420.png
  Frame 2609448.jpg
  Property 1=lg.png
  README.md
  desktop_01.png
  desktop_05.png
  footer.png
  gnb.jpg
  index.html
  login.html
  login_styles.css
  reset.css
  signup.html
  style.css
  필독.md
Labels: 매운맛🔥, 최종 제출

#13 Basic 장래훈 sprint1
  .github/pull-request-template.md
  미션1/1번 배경이미지.png
  미션1/1번펜더이미지.png
  미션1/FAQ.png
  미션1/desktop_01.png
  미션1/index.html
  미션1/pp.png
  미션1/구경하러가기.png
  미션1/로그인.png
  미션1/미션배경1.png
  미션1/미션사진3.png
  미션1/미션사진4.png
  미션1/미션사진5.png
  미션1/미션사진6.png
  미션1/미션사진7.png
  미션1/유튜브.png
  미션1/인스타그램.png
  미션1/일상의 모든 물건을 거래해 보세요.png
  미션1/작은로고.png
  미션1/코드잇마크.png
  미션1/큰로고.png
  미션1/트위터.png
  미션1/판다마켓.css
  미션2-1/btn_large (2).png
  미션2-1/index.html
  미션2-1/style.css
  미션2-1/간편 로그인하기.png
  미션2-1/구글.png
  미션2-1/로그인.png
  미션2-1/로그인1.png
  미션2-1/카카오.png
  미션2-1/판다로고.png
  미션2-1/페북.png
  미션2-2/index.html
  미션2-2/staly.css
  미션2-2/구글.png
  미션2-2/눈모양.png
  미션2-2/카카오.png
  미션2-2/판다로고.png
  미션2-2/회원가입.png
Labels: 미완성🫠, 순한맛🐑

#15 [김주영] sprint 1 + 2
  .DS_Store
  README.md
  css/color_set.css
  css/member.css
  css/reset.css
  css/style.css
  img/.DS_Store
  img/Img_home_01.png
  img/Img_home_02-1.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/desktop_01.jpg
  img/google_login_icon.png
  img/ic_facebook.png
  img/ic_facebook.svg
  img/ic_instagram.png
  img/ic_instagram.svg
  img/ic_twitter.png
  img/ic_twitter.svg
  img/ic_youtube.png
  img/ic_youtube.svg
  img/kakao_login_icon.png
  img/logo.png
  index.html
  js/common.js
  member/login.html
  member/sigin_up.html
  policy/faq.html
  policy/privacy.html
  shop/items.html
Labels: 매운맛🔥, 최종 제출

#9 Basic-김세환 Sprint Mission 1, 2
  README.md
  sprint_mission/.DS_Store
  sprint_mission/faq.html
  sprint_mission/icons/favicon.png
  sprint_mission/icons/google_login_icon.png
  sprint_mission/icons/ic_facebook.png
  sprint_mission/icons/ic_facebook@2x.png
  sprint_mission/icons/ic_facebook@3x.png
  sprint_mission/icons/ic_instagram.png
  sprint_mission/icons/ic_instagram@2x.png
  sprint_mission/icons/ic_instagram@3x.png
  sprint_mission/icons/ic_twitter.png
  sprint_mission/icons/ic_twitter@2x.png
  sprint_mission/icons/ic_twitter@3x.png
  sprint_mission/icons/ic_youtube.png
  sprint_mission/icons/ic_youtube@2x.png
  sprint_mission/icons/ic_youtube@3x.png
  sprint_mission/icons/kakao_login_icon.png
  sprint_mission/images/Img_home_01.png
  sprint_mission/images/Img_home_01@2x.png
  sprint_mission/images/Img_home_01@3x.png
  sprint_mission/images/Img_home_02-1.png
  sprint_mission/images/Img_home_02.png
  sprint_mission/images/Img_home_02@2x.png
  sprint_mission/images/Img_home_03.png
  sprint_mission/images/Img_home_03@2x.png
  sprint_mission/images/Img_home_03@3x.png
  sprint_mission/images/Img_home_bottom.png
  sprint_mission/images/Img_home_bottom@2x.png
  sprint_mission/images/Img_home_bottom@3x.png
  sprint_mission/images/Img_home_top.png
  sprint_mission/images/Img_home_top@2x.png
  sprint_mission/images/Img_home_top@3x.png
  sprint_mission/images/Property 1=Typo.png
  sprint_mission/images/Property 1=Typo@2x.png
  sprint_mission/images/Property 1=Typo@3x.png
  sprint_mission/images/Property 1=lg.png
  sprint_mission/images/Property 1=lg@2x.png
  sprint_mission/images/Property 1=lg@3x.png
  sprint_mission/images/Property 1=md.png
  sprint_mission/images/Property 1=md@2x.png
  sprint_mission/images/Property 1=md@3x.png
  sprint_mission/images/Property 1=sm.png
  sprint_mission/images/Property 1=sm@2x.png
  sprint_mission/images/Property 1=sm@3x.png
  sprint_mission/index.html
  sprint_mission/index.js
  sprint_mission/items.html
  sprint_mission/login.css
  sprint_mission/login.html
  sprint_mission/preview_images/pandamarket_loginpage.png
  sprint_mission/preview_images/pandamarket_mainpage.png
  sprint_mission/preview_images/pandamarket_registerpage.png
  sprint_mission/privacy.html
  sprint_mission/reset.css
  sprint_mission/signup.html
  sprint_mission/styles.css
Labels: 매운맛🔥, 최종 제출

#5 Basic 엄성민 sprint1,2
  project/README.md
  project/faq.html
  project/img/Ic_google.png
  project/img/Ic_kakao.png
  project/img/Img_home_bottom.png
  project/img/Img_home_top.png
  project/img/Img_section2.png
  project/img/Img_section3.png
  project/img/btn_visibility_off.png
  project/img/btn_visibility_on.png
  project/img/ic_facebook.png
  project/img/ic_instagram.png
  project/img/ic_twitter.png
  project/img/ic_youtube.png
  project/img/img_section1.png
  project/img/logo.png
  project/img/panda.png
  project/index.html
  project/items.html
  project/login.html
  project/login.js
  project/privacy.html
  project/reset.css
  project/signup.html
  project/style.css
  project/style_login.css
Labels: 매운맛🔥, 최종 제출

#29 [구은모] sprint3
  faq/faq.html
  index.html
  index.js
  items/items.html
  login/login.html
  login/login.js
  privacy/privacy.html
  signup/signup.html
  signup/signup.js
  style.css
Labels: 순한맛🐑, 진행 중 🏃

#25 [스프린트 미션3] 이현서
  Frame 2609420.png
  Frame 2609448.jpg
  SM1-2/Img_home_01.png
  SM1-2/Img_home_02.png
  SM1-2/Img_home_03.png
  SM1-2/Img_home_bottom.png
  SM1-2/Img_home_top.png
  SM1-2/Property 1=lg.png
  SM1-2/google-logo.png
  SM1-2/ic_facebook.png
  SM1-2/ic_instagram.png
  SM1-2/ic_twitter.png
  SM1-2/ic_youtube.png
  SM1-2/index.html
  SM1-2/kakao-logo.png
  SM1-2/login.html
  SM1-2/login_styles.css
  SM1-2/reset.css
  SM1-2/signup.html
  SM1-2/signup.js
  SM1-2/signup_styles.css
  SM1-2/style.css
  desktop_01.png
  desktop_05.png
  footer.png
  gnb.jpg
  index.html
  login.html
  reset.css
  signup.html
  style.css
Labels: 매운맛🔥, 미완성🫠

#26 [스프린트 미션-3]권용화 (commit : fix:mission-3 start )
  .github/pull_request_template.md
  README1.md
  image/Img_home_01.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/desktop_02.png
  image/desktop_03.png
  image/desktop_04.png
  index.html
  login/login.css
  login/login.html
  login/login.js
  reset.css
  signup/signup.css
  signup/signup.html
  signup/signup.js
Labels: 최종 제출

#33 Basic 정진호 sprint3
  default_data.js
  login.css
  login.html
  login.js
  signup.css
  signup.html
  signup.js
Labels: 매운맛🔥, 최종 제출

#31 [김주영] Sprint3
  SPRINT3-PR.md
  index.html
  js/common.js
  member/login.html
  member/sigin_up.html
Labels: 매운맛🔥, 미완성🫠, 최종 제출

#36 이현서 [스프린트 미션4] 제출
  SM1-2/ArticleService.js
  SM1-2/ProductService.js
  SM1-2/main.js
  SM1-2/package.json
  {
Labels: 순한맛🐑, 최종 제출

#38 Basic 정진호 sprint4
  sprint_4/ArticleService.js
  sprint_4/ProductService.js
  sprint_4/index.html
  sprint_4/main.js
Labels: 매운맛🔥, 최종 제출

#34 Basic 엄성민 sprint4
  .vscode/launch.json
  ArticleService.js
  ProductService.js
  main.js
Labels: 매운맛🔥, 최종 제출
